### ISSUE TITLE
Skeleton

### ISSUE THREAD

**Issue by lobos22** [demtor/MyBB-2FA#1]
I dont know but I think adding an option if we want to enable or disable "Skeleton"

I dont know why you have it, Since we are force to enter 123 and not anyother PIN
Thank you

**Comment by demtor** [comment]
The Skeleton method is a method that I am using for testing purposes. For now you can disable a method prefixing the method class filename with a dot, so for Skeleton you need to rename `inc/plugins/my2fa/methods/Skeleton.php` to `inc/plugins/my2fa/methods/.Skeleton.php`. It is necessary to uninstall and install the plugin again after doing this. More details on how to disable a 2FA method without uninstalling and installing everytime will be available soon, I need before to complete a rebuild option.

Let me remind that this is an alpha release, it is highly not suggested for production use (I am not sure if this is your case).

**Comment by lobos22** [comment]
I think I have to wait for the stable realease
